---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: install nginx collections
      #command: "ansible-galaxy collection install --roles-path /etc/ansible/roles nginxinc.nginx_core"
      command: "chdir=/etc/ansible/roles ansible-galaxy collection install nginxinc.nginx_core"
      register: output
    - name: list collections
      command: "ls -la /etc/ansible/roles"
      register: output
    - debug: var=output

- hosts: all
  gather_facts: no
  tasks:
    - name: Include the example role
      include_role:
        name: nginx

#- hosts: all
  #collections:
    #- nginxinc.nginx_core
  #roles:
    #- role: nginx
