---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: install nginx collections
      command: "ansible-galaxy collection install nginxinc.nginx_core"
      register: output

- hosts: all
  gather_facts: no
  tasks:
    - name: Include the example role
      include_role:
        name: nginx
#---
#- hosts: all
  #collections:
    #- nginxinc.nginx_core
  #roles:
    #- role: nginx
